#!/bin/bash

for file in *.html
do
  if [ -f "../$file" ]
  then
    if [ "$file" -nt "../$file" ]
    then
      cp "$file" "../$file"
      echo "Copied $file to parent directory."
    fi
  else
    cp "$file" "../$file"
    echo "Copied $file to parent directory."
  fi
done
